name: Launch Streamlit Chatbot

on:  
  push:  
    branches: [main]  # Runs when pushing to 'main'
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  launch-chatbot:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pull latest code from repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use Python 3.10

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies, including Streamlit

      - name: Run Streamlit Application
        run: |
          nohup streamlit run main.py --server.port 8501 --server.headless true &  # Run in background
        working-directory: ${{ github.workspace }}  # Ensure it's running in the correct directory

      - name: Keep Runner Alive
        run: sleep 3600  # Keeps the runner alive for an hour
